/usr/bin/python2.7 /Users/simo/Documents/Studies/MVA/pgm/homeworks/hwk1/main.py

LDA_Dataset_A:

The bernoulli parameter pi is 
0.333333333333

The mean for the class {y=0} is 
[[ 2.89970947 -0.893874  ]]

The mean for the class {y=1} is 
[[-2.69232004  0.866042  ]]

Sigma is: 
[[ 2.44190897 -1.13194024]
 [-1.13194024  0.61375465]]

Training misclassification error is: 1.33 %

Test misclassification error is: 2.00 %


Logistic_Regression_Dataset_A:

iteration 1
iteration 2
iteration 3
iteration 4
iteration 5
iteration 6
iteration 7
iteration 8
iteration 9
iteration 10
iteration 11
iteration 12
iteration 13
iteration 14
iteration 15
iteration 16
iteration 17
Some computation gives back a double too large to be represented, most certainly in w

The learnt parameter w is: 
[[-276.80419556]
 [-479.25803481]]


The learnt parameter b is: 
-46.2785737314

Training misclassification error is: 0.00 %

Test misclassification error is: 3.40 %


Linear_Regression_Dataset_A

The learnt parameter w is: 
[[-0.2640075 ]
 [-0.37259311]]


The learnt parameter b is: 
-46.2785737314

The variance of Y computed for the latter w is: 
[[ 0.03986552]]

Training misclassification error is: 1.33 %

Test misclassification error is: 2.07 %


QDA_Dataset_A:

The bernoulli parameter pi is 
0.333333333333

The mean for the class {y=0} is 
[[ 2.89970947 -0.893874  ]]

The mean for the class {y=1} is 
[[-2.69232004  0.866042  ]]

Sigma for the class {y=0} is: 
[[ 2.31065259 -1.04748461]
 [-1.04748461  0.57578403]]

Sigma for the class {y=1} is: 
[[ 2.70442172 -1.3008515 ]
 [-1.3008515   0.68969588]]

Training misclassification error is: 0.67 %

Test misclassification error is: 2.00 %


LDA_Dataset_B:

The bernoulli parameter pi is 
0.5

The mean for the class {y=0} is 
[[ 3.34068896 -0.83546333]]

The mean for the class {y=1} is 
[[-3.21670734  1.08306733]]

Sigma is: 
[[ 3.34623467 -0.13516489]
 [-0.13516489  1.73807475]]

Training misclassification error is: 3.00 %

Test misclassification error is: 4.15 %


Logistic_Regression_Dataset_B:

iteration 1
iteration 2
iteration 3
iteration 4
iteration 5
iteration 6
iteration 7
iteration 8
iteration 9
iteration 10
iteration 11
iteration 12
iteration 13
iteration 14
iteration 15
iteration 16
iteration 17
iteration 18
iteration 19
iteration 20

The learnt parameter w is: 
[[-1.70518586]
 [ 1.02378538]]


The learnt parameter b is: 
1.34959157315

Training misclassification error is: 2.00 %

Test misclassification error is: 4.30 %


Linear_Regression_Dataset_B

The learnt parameter w is: 
[[-0.10424575]
 [ 0.05179118]]


The learnt parameter b is: 
1.34959157315

The variance of Y computed for the latter w is: 
[[ 0.05426408]]

Training misclassification error is: 3.00 %

Test misclassification error is: 4.15 %


QDA_Dataset_B:

The bernoulli parameter pi is 
0.5

The mean for the class {y=0} is 
[[ 3.34068896 -0.83546333]]

The mean for the class {y=1} is 
[[-3.21670734  1.08306733]]

Sigma for the class {y=0} is: 
[[ 2.53885859  1.0642112 ]
 [ 1.0642112   2.96007891]]

Sigma for the class {y=1} is: 
[[ 4.15361075 -1.33454097]
 [-1.33454097  0.51607059]]

Training misclassification error is: 1.33 %

Test misclassification error is: 2.00 %


LDA_Dataset_C:

The bernoulli parameter pi is 
0.625

The mean for the class {y=0} is 
[[ 2.79304824 -0.83838667]]

The mean for the class {y=1} is 
[[-2.94232885 -0.9578284 ]]

Sigma is: 
[[ 2.88039225 -0.63405081]
 [-0.63405081  5.19952435]]

Training misclassification error is: 5.50 %

Test misclassification error is: 4.23 %


Logistic_Regression_Dataset_C:

iteration 1
iteration 2
iteration 3
iteration 4
iteration 5
iteration 6
iteration 7
iteration 8
iteration 9
iteration 10
iteration 11
iteration 12
iteration 13
iteration 14
iteration 15
iteration 16
iteration 17
iteration 18
iteration 19
iteration 20

The learnt parameter w is: 
[[-2.2032324 ]
 [ 0.70926562]]


The learnt parameter b is: 
0.959188854105

Training misclassification error is: 4.00 %

Test misclassification error is: 2.27 %


Linear_Regression_Dataset_C

The learnt parameter w is: 
[[-0.12769333]
 [-0.01700142]]


The learnt parameter b is: 
0.959188854105

The variance of Y computed for the latter w is: 
[[ 0.06224998]]

Training misclassification error is: 5.50 %

Test misclassification error is: 4.23 %


QDA_Dataset_C:

The bernoulli parameter pi is 
0.625

The mean for the class {y=0} is 
[[ 2.79304824 -0.83838667]]

The mean for the class {y=1} is 
[[-2.94232885 -0.9578284 ]]

Sigma for the class {y=0} is: 
[[ 2.89913927  1.24581553]
 [ 1.24581553  2.92475448]]

Sigma for the class {y=1} is: 
[[ 2.86914403 -1.76197061]
 [-1.76197061  6.56438626]]

Training misclassification error is: 5.25 %

Test misclassification error is: 3.83 %

/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x10667cbd0>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x106702310>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x107073c90>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x10f917ad0>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x10f950910>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x10fe7f590>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x1072af350>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x10667c590>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x106ff77d0>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x1055d2650>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x107059d50>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x10669f750>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x1072c9350>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x10fa20a90>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x10ff2fd50>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x1071579d0>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x107138090>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x106667590>]
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support <matplotlib.contour.QuadContourSet instance at 0x10701b1b8>
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support <matplotlib.contour.QuadContourSet instance at 0x1072bd560>
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support <matplotlib.contour.QuadContourSet instance at 0x105545878>
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support <matplotlib.contour.QuadContourSet instance at 0x10553c710>
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support <matplotlib.contour.QuadContourSet instance at 0x10553f680>
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/legend.py:613: UserWarning: Legend does not support <matplotlib.contour.QuadContourSet instance at 0x10709d1b8>
Use proxy artist instead.

http://matplotlib.sourceforge.net/users/legend_guide.html#using-proxy-artist

  (str(orig_handle),))

Process finished with exit code 0

